name: PocketFightBot
version: 2.0.0
api: [5.0.0]
main: PocketFightBot\Main
author: PocketFightBot, OfficialLilKev
description: Advanced PvP Practice Bot

commands:
  fightbot:
    description: Spawn a PvP bot to practice against
    permission: fightbot.cmd

permissions:
  fightbot.cmd:
    default: op
    description: Allows spawning the fight bot
